site_name: Alek's Blog
site_url: https://blog.kirilov.dev

theme:
  name: material
  custom_dir: overrides

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  favicon: images/favicon.ico
  logo: images/favicon.ico
  features:
    - content.code.copy
    - navigation.indexes
    - content.tooltips
    - content.footnote.tooltips
    - navigation.footer

extra:
  social:
    - link: https://www.linkedin.com/in/alexander-kirilov-b0373a62/
      icon: fontawesome/brands/linkedin
    - link: https://github.com/sashokbg/
      icon: fontawesome/brands/github
    - link: https://forms.gle/urr1FeuvyW8fZL1e9
      icon: fontawesome/solid/paper-plane

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox
  - tags
  - blog:
      blog_dir: .
      blog_toc: true

nav:
  - About Me: about_me.md
  - Curriculum Vitae: cv.md
  - Contact: contact.md
  - Home: index.md
